# Generated by Django 4.1.6 on 2023-02-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('cms', '0009_theme_themeindexpage_homepage_theme_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='theme',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
