# Generated by Django 4.1.6 on 2023-02-27 17:30

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_theme_locale_theme_translation_key'),
    ]

    operations = [
        BootstrapTranslatableModel('cms.Theme'),
    ]
